version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: drupal_postgres
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal_user
      POSTGRES_PASSWORD: drupal_password
    networks:
      - drupal
    volumes:
      - postgres_data:/var/lib/postgresql/data

  drupal:
    image: drupal:9
    container_name: drupal_site
    depends_on:
      - postgres
    environment:
      DRUPAL_DB_HOST: drupal_postgres
      DRUPAL_DB_PORT: 5432
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal_user
      DRUPAL_DB_PASSWORD: drupal_password
    ports:
      - "8080:80"
    networks:
      - drupal

networks:
  drupal:
    driver: bridge

volumes:
  postgres_data:
